[package]
name = "icmsg"
version = "0.0.1"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "Rust implementation of the ICMsg IPC backend"

[dependencies]
elain = "0.3.1"
embassy-futures = "0.1.1"
embedded-hal-async = "1.0.0"

[dev-dependencies]
tokio = { version = "1.44.2", features = ["macros", "rt-multi-thread", "sync", "time"] }
