[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# replace nRF82840_xxAA with your chip as listed in `probe-rs chip list`
runner = "probe-rs run --chip nRF5340_xxAA"

[build]
target = "thumbv8m.main-none-eabihf"
rustflags = "-C target-cpu=cortex-m33 -C force-frame-pointers"

[patch."https://github.com/embassy-rs/trouble.git"]
trouble-host = { path = "../../../../../forks/trouble/host" }
